language: scala
scala:
   - 2.11.4
jdk:
   - oraclejdk7
addons:
  apt:
    packages:
    - libatlas3gf-base
    - libopenblas-base   
sbt_args: -Dcom.github.fommil.netlib.BLAS=com.github.fommil.netlib.F2jBLAS -Dcom.github.fommil.netlib.LAPACK=com.github.fommil.netlib.F2jLAPACK -Dcom.github.fommil.netlib.ARPACK=com.github.fommil.netlib.F2jARPACK
cache:
  directories:
  - $HOME/.ivy2
script: "sbt clean coverage test"
